stream_ip: 192.168.1.236
stream_port: 9801
redis_ip: 192.168.1.17
redis_port: 6379

default_maximum_temperature: 80
default_minimum_temperature: 15

features:
  file_logging: false
  demo_mode: false
  disable_stove_connector: true